-- Drops para apagar possiveis tabelas existentes
DROP TABLE gs_el_notificacoes CASCADE CONSTRAINTS;
DROP TABLE gs_el_relatorios_turno CASCADE CONSTRAINTS;
DROP TABLE gs_el_turnos CASCADE CONSTRAINTS;
DROP TABLE gs_el_alertas CASCADE CONSTRAINTS;
DROP TABLE gs_el_niveis_operacionais CASCADE CONSTRAINTS;
DROP TABLE gs_el_limites_reator CASCADE CONSTRAINTS;
DROP TABLE T_status_notificacao CASCADE CONSTRAINTS;
DROP TABLE gs_el_operadores CASCADE CONSTRAINTS;
DROP TABLE gs_el_reatores CASCADE CONSTRAINTS;

-------------------------------------------------------------------------------------------------------------


CREATE TABLE gs_el_reatores (
    reator_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(50) NOT NULL,
    localizacao VARCHAR2(100)
);

-------------------------------------------------------------------------------------------------------------

CREATE TABLE gs_el_operadores (
    operador_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(50) NOT NULL,
    cargo VARCHAR2(50)
);

-------------------------------------------------------------------------------------------------------------

create table gs_el_status_notificacao (
    STATUS_NOTIFICACAO_ID number generated by default as identity primary key,
    DESCRICAO varchar2(50) not null
);


-------------------------------------------------------------------------------------------------------------

CREATE TABLE gs_el_niveis_operacionais (
    nivel_operacional_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reator_id NUMBER NOT NULL,
    data_hora_medicao DATE NOT NULL,
    pressao NUMBER,
    temperatura NUMBER,
    radiacao NUMBER
);

ALTER TABLE gs_el_niveis_operacionais
ADD CONSTRAINT fk_niveis_reatores
FOREIGN KEY (reator_id) REFERENCES gs_el_reatores(reator_id);



-------------------------------------------------------------------------------------------------------------

CREATE TABLE gs_el_alertas (
    alerta_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reator_id NUMBER NOT NULL,
    data_hora_alerta DATE NOT NULL,
    tipo_alerta VARCHAR2(50),
    nivel_critico VARCHAR2(20)
);

ALTER TABLE gs_el_alertas
ADD CONSTRAINT fk_alertas_reatores
FOREIGN KEY (reator_id) REFERENCES gs_el_reatores(reator_id);



-------------------------------------------------------------------------------------------------------------

CREATE TABLE gs_el_turnos (
    turno_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operador_id NUMBER NOT NULL,
    data_inicio DATE NOT NULL,
    data_fim DATE
);

ALTER TABLE gs_el_turnos
ADD CONSTRAINT fk_turnos_operadores
FOREIGN KEY (operador_id) REFERENCES gs_el_operadores(operador_id);

-------------------------------------------------------------------------------------------------------------

CREATE TABLE gs_el_relatorios_turno (
    relatorio_turno_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operador_id NUMBER NOT NULL,
    data_hora_relatorio DATE NOT NULL,
    resumo_atividades VARCHAR2(200),
    observacoes VARCHAR2(300)
);

ALTER TABLE gs_el_relatorios_turno
ADD CONSTRAINT fk_relatorios_turno_operadores
FOREIGN KEY (operador_id) REFERENCES gs_el_operadores(operador_id);

-------------------------------------------------------------------------------------------------------------

CREATE TABLE gs_el_limites_reator (
    limite_reator_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reator_id NUMBER NOT NULL,
    limite_pressao NUMBER,
    limite_temperatura NUMBER,
    limite_radiacao NUMBER
);

ALTER TABLE gs_el_limites_reator
ADD CONSTRAINT fk_limites_reator
FOREIGN KEY (reator_id) REFERENCES gs_el_reatores(reator_id);

-------------------------------------------------------------------------------------------------------------

CREATE TABLE gs_el_notificacoes (
    notificacao_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_hora_notificacao DATE NOT NULL,
    operador_id NUMBER NOT NULL,
    alerta_id NUMBER NOT NULL,
    status_notificacao_id NUMBER
);

ALTER TABLE gs_el_notificacoes
ADD CONSTRAINT fk_notificacoes_alertas
FOREIGN KEY (alerta_id) REFERENCES gs_el_alertas(alerta_id);

ALTER TABLE gs_el_notificacoes
ADD CONSTRAINT fk_notificacoes_operadores
FOREIGN KEY (operador_id) REFERENCES gs_el_operadores(operador_id);

-------------------------------------------------------------------------------------------------------------

/*
GS_EL_REATORES: Armazena informações dos reatores nucleares, incluindo seu nome e localização. Serve como referência para identificar os reatores monitorados.

GS_EL_NIVEIS_OPERACIONAIS: Registra as leituras dos níveis operacionais dos reatores, como pressão, temperatura e radiação, permitindo monitoramento contínuo.

GS_EL_ALERTAS: Contém registros de alertas gerados quando os níveis de operação excedem os limites normais, indicando a necessidade de ação imediata.

GS_EL_NOTIFICACOES: Registra as notificações enviadas aos operadores em resposta aos alertas, com o status de cada notificação para acompanhamento.

GS_EL_OPERADORES: Armazena informações sobre os operadores responsáveis pelo monitoramento dos reatores, incluindo nome, cargo e turno.

GS_EL_TURNOS: Registra os turnos de trabalho dos operadores, incluindo horários de início e término, facilitando o acompanhamento das atividades e dos responsáveis em cada turno.

GS_EL_RELATORIOS_TURNO: Armazena relatórios diários feitos pelos operadores ao final de cada turno, com um resumo das atividades e observações importantes.

GS_EL_LIMITES_REATOR: Define os limites máximos aceitáveis de pressão, temperatura e radiação para cada reator, usados como referência para disparo de alertas.

GS_EL_STATUS_NOTIFICACAO: Lista os possíveis status das notificações (como "Enviado", "Visualizado", "Confirmado"), ajudando a acompanhar o estado de cada notificação enviada aos operadores.
*/