DROP TABLE gs_el_historico_notificacoes CASCADE CONSTRAINTS;
DROP TABLE gs_el_historico_relatorio CASCADE CONSTRAINTS;
DROP TABLE gs_el_localizacao_reator CASCADE CONSTRAINTS;
DROP TABLE gs_el_niveis_operacionais CASCADE CONSTRAINTS;
DROP TABLE gs_el_notificacoes CASCADE CONSTRAINTS;
DROP TABLE gs_el_operadores CASCADE CONSTRAINTS;
DROP TABLE gs_el_reatores CASCADE CONSTRAINTS;
DROP TABLE gs_el_relatorios_turno CASCADE CONSTRAINTS;
DROP TABLE gs_el_status_notificacao CASCADE CONSTRAINTS;
DROP TABLE gs_el_tipo_reator CASCADE CONSTRAINTS;
DROP TABLE gs_el_turnos CASCADE CONSTRAINTS;


-------------------------------------------------------------------------------------------------------------------------------------------

CREATE TABLE gs_el_historico_notificacoes (
    hist_notificacao_id         NUMBER GENERATED BY DEFAULT AS IDENTITY,
    data_hora_atualizacao_notif TIMESTAMP NOT NULL,
    observacao_notificacao      VARCHAR2(250),
    notificacao_id              NUMBER(20) NOT NULL
);

CREATE UNIQUE INDEX gs_el_historico_notificacoes__idx ON
    gs_el_historico_notificacoes (
        notificacao_id
    ASC );

ALTER TABLE gs_el_historico_notificacoes ADD CONSTRAINT gs_el_historico_notificacoes_pk PRIMARY KEY ( hist_notificacao_id );

-------------------------------------------------------------------------------------------------------------------------------------------

CREATE TABLE gs_el_historico_relatorio (
    hist_relatorio_id     NUMBER GENERATED BY DEFAULT AS IDENTITY,
    data_hora_atualizacao TIMESTAMP NOT NULL,
    observacoes           VARCHAR2(150),
    relatorio_turno_id    NUMBER(20) NOT NULL
);

ALTER TABLE gs_el_historico_relatorio ADD CONSTRAINT gs_el_historico_relatorio_pk PRIMARY KEY ( hist_relatorio_id );

-------------------------------------------------------------------------------------------------------------------------------------------

CREATE TABLE gs_el_localizacao_reator (
    loc_reator_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    setor         VARCHAR2(50) NOT NULL,
    unidade       VARCHAR2(20) NOT NULL,
    descricao     VARCHAR2(250)
);

ALTER TABLE gs_el_localizacao_reator ADD CONSTRAINT gs_el_localizacao_reator_pk PRIMARY KEY ( loc_reator_id );

-------------------------------------------------------------------------------------------------------------------------------------------

CREATE TABLE gs_el_niveis_operacionais (
    nivel_operacional_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    data_hora_medicao    TIMESTAMP NOT NULL,
    pressao              NUMBER(20) NOT NULL,
    temperatura          NUMBER(20) NOT NULL,
    radiacao             NUMBER(20) NOT NULL,
    fluxo_refrigeracao   NUMBER(20) NOT NULL,
    reator_id            NUMBER(20) NOT NULL
);

ALTER TABLE gs_el_niveis_operacionais ADD CONSTRAINT gs_el_niveis_operacionais_pk PRIMARY KEY ( nivel_operacional_id );

-------------------------------------------------------------------------------------------------------------------------------------------

CREATE TABLE gs_el_notificacoes (
    notificacao_id        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    data_hora_notificacao TIMESTAMP NOT NULL,
    status_notificacao_id NUMBER(20) NOT NULL,
    operador_id           NUMBER(20) NOT NULL,
    reator_id             NUMBER(20) NOT NULL
);

ALTER TABLE gs_el_notificacoes ADD CONSTRAINT gs_el_notificacoes_pk PRIMARY KEY ( notificacao_id );

-------------------------------------------------------------------------------------------------------------------------------------------

CREATE TABLE gs_el_operadores (
    operador_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome_operador  VARCHAR2(50) NOT NULL,
    senha_operador VARCHAR2(50) NOT NULL,
    cargo          VARCHAR2(50) NOT NULL,
    turno_id       NUMBER(20) NOT NULL,
    lor            VARCHAR2(30) NOT NULL
);

ALTER TABLE gs_el_operadores ADD CONSTRAINT gs_el_operadores_pk PRIMARY KEY ( operador_id );

ALTER TABLE gs_el_operadores ADD CONSTRAINT gs_el_operadores_lor_un UNIQUE ( lor );

-------------------------------------------------------------------------------------------------------------------------------------------

CREATE TABLE gs_el_reatores (
    reator_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome_reator     VARCHAR2(50) NOT NULL,
    pressao_max     NUMBER(20) NOT NULL,
    temperatura_max NUMBER(20) NOT NULL,
    radiacao_max    NUMBER(20) NOT NULL,
    fluxo_refrigeracao_max    NUMBER(20) NOT NULL,
    tipo_reator_id  NUMBER(20) NOT NULL,
    loc_reator_id   NUMBER(20) NOT NULL
);

CREATE UNIQUE INDEX gs_el_reatores__idx ON
    gs_el_reatores (
        loc_reator_id
    ASC );

ALTER TABLE gs_el_reatores ADD CONSTRAINT gs_el_reatores_pk PRIMARY KEY ( reator_id );

-------------------------------------------------------------------------------------------------------------------------------------------

CREATE TABLE gs_el_relatorios_turno (
    relatorio_turno_id  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    data_hora_relatorio DATE NOT NULL,
    resumo_atividades   VARCHAR2(200) NOT NULL,
    observacoes         VARCHAR2(300),
    operador_id         NUMBER(20) NOT NULL,
    reator_id           NUMBER(20) NOT NULL
);

ALTER TABLE gs_el_relatorios_turno ADD CONSTRAINT gs_el_relatorios_turno_pk PRIMARY KEY ( relatorio_turno_id );

-------------------------------------------------------------------------------------------------------------------------------------------

CREATE TABLE gs_el_status_notificacao (
    status_notificacao_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    descr_status          VARCHAR2(200)
);

ALTER TABLE gs_el_status_notificacao ADD CONSTRAINT gs_el_status_notificacao_pk PRIMARY KEY ( status_notificacao_id );

-------------------------------------------------------------------------------------------------------------------------------------------

CREATE TABLE gs_el_tipo_reator (
    tipo_reator_id     NUMBER GENERATED BY DEFAULT AS IDENTITY,
    descricao_reator   VARCHAR2(200) NOT NULL,
    capacidade_energia NUMBER(30) NOT NULL,
    tecnologia         VARCHAR2(50) NOT NULL,
    fabricante         VARCHAR2(50) NOT NULL
);

ALTER TABLE gs_el_tipo_reator ADD CONSTRAINT gs_el_tipo_reator_pk PRIMARY KEY ( tipo_reator_id );

-------------------------------------------------------------------------------------------------------------------------------------------

CREATE TABLE gs_el_turnos (
    turno_id        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    descricao_turno VARCHAR2(50) NOT NULL
);

ALTER TABLE gs_el_turnos ADD CONSTRAINT gs_el_turnos_pk PRIMARY KEY ( turno_id );

-------------------------------------------------------------------------------------------------------------------------------------------

ALTER TABLE gs_el_reatores
    ADD CONSTRAINT gs_el_localizacao_reator_fk FOREIGN KEY ( loc_reator_id )
        REFERENCES gs_el_localizacao_reator ( loc_reator_id );

ALTER TABLE gs_el_historico_notificacoes
    ADD CONSTRAINT gs_el_notificacoes_fk FOREIGN KEY ( notificacao_id )
        REFERENCES gs_el_notificacoes ( notificacao_id );

ALTER TABLE gs_el_notificacoes
    ADD CONSTRAINT gs_el_operadores_fk FOREIGN KEY ( operador_id )
        REFERENCES gs_el_operadores ( operador_id );

ALTER TABLE gs_el_relatorios_turno
    ADD CONSTRAINT gs_el_operadores_fkv1 FOREIGN KEY ( operador_id )
        REFERENCES gs_el_operadores ( operador_id );

ALTER TABLE gs_el_niveis_operacionais
    ADD CONSTRAINT gs_el_reatores_fk FOREIGN KEY ( reator_id )
        REFERENCES gs_el_reatores ( reator_id );

ALTER TABLE gs_el_relatorios_turno
    ADD CONSTRAINT gs_el_reatores_fkv1 FOREIGN KEY ( reator_id )
        REFERENCES gs_el_reatores ( reator_id );

ALTER TABLE gs_el_notificacoes
    ADD CONSTRAINT gs_el_reatores_fkv2 FOREIGN KEY ( reator_id )
        REFERENCES gs_el_reatores ( reator_id );

ALTER TABLE gs_el_historico_relatorio
    ADD CONSTRAINT gs_el_relatorios_turno_fk FOREIGN KEY ( relatorio_turno_id )
        REFERENCES gs_el_relatorios_turno ( relatorio_turno_id );

ALTER TABLE gs_el_notificacoes
    ADD CONSTRAINT gs_el_status_notificacao_fk FOREIGN KEY ( status_notificacao_id )
        REFERENCES gs_el_status_notificacao ( status_notificacao_id );

ALTER TABLE gs_el_reatores
    ADD CONSTRAINT gs_el_tipo_reator_fk FOREIGN KEY ( tipo_reator_id )
        REFERENCES gs_el_tipo_reator ( tipo_reator_id );

ALTER TABLE gs_el_operadores
    ADD CONSTRAINT gs_el_turnos_fk FOREIGN KEY ( turno_id )
        REFERENCES gs_el_turnos ( turno_id );

-------------------------------------------------------------------------------------------------------------------------------------------